version: "3.9"
services:
  redis_db:
    env_file:
      - .env
    volumes:
      - "${DATABASE_FS_MOUNT}/redis:/data"
  db:
    env_file:
      - .env
    environment:
      POSTGRES_DB: dm2_production
      POSTGRES_USER: "${DM2_DATABASE_USER}"
      POSTGRES_PASSWORD: "${DM2_DATABASE_PASSWORD}"
    volumes:
      - "${DATABASE_FS_MOUNT}/postgresql:/var/lib/postgresql/data"

  app:
    restart: always
    command: bash -c "rm -f tmp/pids/server.pid && cd /opt/app && foreman start -f Procfile.prod"
    environment: # May be overridden by values in .env
      DATABASE_URL: postgres://${DM2_DATABASE_USER}:${DM2_DATABASE_PASSWORD}@db
      RACK_ENV: production
      RAILS_ENV: production
      REDIS_URL: redis://redis_db:6379
      REDIS_PROVIDER: REDIS_URL
    ports:
      - "443:443"